AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to backsync claim status to oracle db
Resources:
  ClaimsBacksync:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ClaimsBacksync
      Handler: org.octank.claims.oracle.main.ClaimsBacksyncHandler
      Runtime: java8
      CodeUri: s3://octank-healthcare/octank-claims-backsync-1.0-SNAPSHOT.jar
      Description: Backsync Claims
      Timeout: 120
      MemorySize: 1024
      VpcConfig: # For accessing RDS instance
        SecurityGroupIds:
          - sg-019cfb0716e6f65ab
        SubnetIds:
          - subnet-be396bc7
          - subnet-379ae67c 
      Environment:
        Variables:
          RDS_HOSTNAME: 172.31.17.106:1521:orcl
          RDS_DB_NAME: CLAIMS
          RDS_USERNAME: claims
          RDS_PASSWORD: claims123
      Role: arn:aws:iam::716664005094:role/microServiceRole
